spring:
  datasource:
    url: jdbc:mysql://localhost:3306/securitytest?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver


  redis:
    host: localhost
    port: 6379
  mybatis-plus:
    mapper-locations: classpath*:/mapper/**/*.xml